### PR TITLE
Edits to README.md and CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by awu556**
Hey guys, I made some more alterations to the README.md for grammar, wording, etc. I also added some more directions to the CONTRIBUTING.md regarding forking the main repo, where to find the REACT_APP_QA_URL, and how to set up an upstream repo via Git so everyone can pull current versions to their forked repo

### CODE REVIEW

**Comment by SomeMoosery** [comment]
Hey @awu556 - these changes look great, thanks so much for stepping up and and contributing so much so fast! If you could just rebase off of master (I assume this is the cause of the merge conflict) this looks good to merge 👍

**Comment by awu556** [comment]
Oh wait, it looks like the readme changed from the last time I saw it, I would hold off on merging

**Comment by ngiangre** [comment]
Hy sorry y'all I've been revising the readme on master - my bad. But check out what I did and see if you like my edits or not. Sorry I need to follow contributing.md :/

**Comment by awu556** [comment]
Oh I see Nick is also adding stuff, I'll just wait till he finishes with changes  to the readme before I commit mine

**Comment by awu556** [comment]
It's all good! Let me know when you're finished and I'll make sure that my branch is matched with everything you have currently for the readme

**Pull request closed without merging**
