### PR TITLE
HOTFIX: Changes necessary to deploy React build

### PR DESCRIPTION
**Pull request by SomeMoosery**
No issue as these are necessary fixes that needed to be completed on the spot for the build to deploy to S3.

### CODE REVIEW

**Comment by tesla809** [comment]
LGTM!

**Comment by tesla809** [comment]
Type error causing CI tests to fail.

Error messages pop up:

Error: Uncaught [TypeError: Cannot read property 'dataSample' of undefined]

  TypeError: Cannot read property 'dataSample' of undefined
    >  8 | const dataSample = useSelector(state => state.root.dataSample);

**Comment by SomeMoosery** [comment]
We can leave this open until it's resolved, but I think this is an error with our current package management. Even a fresh install of master fails these tests now.

I think we should be more diligent about ensuring everyone is using yarn, and that every PR is rebased off the most current master. Babel 7.8.7 has been sneaking back in constantly, and will break tests/builds as it was a broken release

**Comment by tesla809** [comment]
Great points @SomeMoosery. Working on the CONTRIBUTING.md and adding the language around rebasing off the current master. 

I will add the information to alert the devs only to use Yarn.

**Comment by SomeMoosery** [comment]
Actually, while it's good we stay up to date in our package.json of course, this also looks to be a more systemic problem. It's `create-react-app`'s [pinned issue](https://github.com/facebook/create-react-app/issues/8680) right now

**Pull request merged**
