### PR TITLE
Add og:image tag

### LINKED ISSUE #567: Add meta og:image tag in index.html
Add a meta og:image tag in index.html with an image of the homepage (or any other page) of the app. 

## Motivation

When the app link is posted on LinkedIn, other social media, etc., the post will show an image of the app. Currently, it is blank.  

Screen Shot 2020-04-17 at 7 17 52 PM

### PR DESCRIPTION
**Pull request by tylerd92**
# ⚠️ __IMPORTANT: Please do not create a Pull Request without creating an Issue first.__

All changes need to be discussed before proceeding. Failure to do so may result in the pull request being rejected.

Before submitting a pull request, please be sure to review:
- Our Code of Conduct: https://github.com/COVID-19-electronic-health-system/.github/blob/master/CODE_OF_CONDUCT.md
- Our Contributing Guidelines: https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md
- Our Support documentation: https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md

-----

## Please include the issue number the pull request fixes by replacing YOUR-ISSUE-HERE in the text below.

Fixes #567 

## Summary
Added og:image tag to index.html

## Details
Added a screenshot of the health log page and put it in the public folder. Then I added the og:image tag to index.html.

## Final Checklist

- [X] For CoronaTracker, did you bump the version in `package.json`?
    - Update the second decimal for a major change
    - Update the third decimal for a minor change
    - Numbers can go past 9, e.g. `1.0.9` => `1.0.10`
    - For more info, read about [Semantic Versioning](https://semver.org/)
- [ ] Did you add any new tests as necessary?
- [X] Is your PR rebased off the most current master?
- [ ] Have you squashed all commits? _(can be done at merge)_
- [X] Did you use `yarn` not `npm`? _(important!)_
- [ ] Did you use Material-UI wherever possible?
- [ ] Did you run `yarn lint` on the code?
- [X] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by pavel-ilin** [comment]
We should upload image into AWS S3 storage and then add this image to [this](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/client/src/utils/imgUrl.js) helper function and then import image to the component.

I'm happy to help with AWS and helper function if needed.

**Comment by tylerd92** [comment]
I'm not sure if the helper function would work since the image is in a meta tag in the head element of the index.html page. The image itself can be added to the S3 bucket and I think the src could refer to it that way.

**Comment by AdhamAH** [comment]
@tylerd92 So the best thing as agreed to put it in S3. @pavel-ilin and I will be working on it tomorrow so will be uploading the image and provide you with the link

**Comment by tylerd92** [comment]
I removed the image from the public folder and put the image in the S3 bucket. I replaced the link with the link to the [cdn](https://dg1fd6ea8poyj.cloudfront.net/images/myHealthLog.png). If @AdhamAH or @acthelemann would like me to use @pavel-ilin's suggestion I would consider adding that in.

**Pull request merged**
