### PR TITLE
Redux for symptom tracker survey

### PR DESCRIPTION
**Pull request by liadove**
fixes https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/204
I thought you were right we need to save all responses before they submit the survey, in case if they press on other tab and want to come back to survey

### CODE REVIEW

**Comment by SomeMoosery** [comment]
Needs a rebase off of master. I'm sorry, but I'm honestly still a little bit confused why we feel it necessary to store state in redux. Aren't we just maintaining this user state within the component? And don't necessarily need to store anything to Redux? I think it's fair to say that if the user navigates away from this page their progress can be lost, as we only want to save responses when they submit the survey, otherwise things can get messy/confusing.

@fallon7284 I know you explained this in #204 which is why we closed it. Am I missing anything?

**Comment by fallon7284** [comment]
I'm running out for a while and won't be able to give this PR a real look until a good bit later...
Having said that, the flow I'd expect from a survey submission, regarding like local state, database, redux would be: Form fields are stored in state inside the survey component.  Connected component gets a thunk action creator from redux.  Thunk handles asynchronously posting the survey data to the database and then persisting the data from the response in the redux store.  I don't 100% understand the desired flow of the app or what data we expect to use in the front end, @SomeMoosery, so I don't totally understand whether you'd want that survey data added to the redux store at all, though my gut says that you would, so that you could, for example, have components that show the change in survey answers over time.  But certainly you'd only want to persist the data to the redux store as a result of first posting it to the database.

**Comment by SomeMoosery** [comment]
Sounds good, and no problem! Thanks for the good writeup. Yeah, that's what I was really getting at @fallon7284 - I don't think we need to be storing state of the component as it's being filled out in Redux, only on submission. As we chatted about, I'll get a much clearer vision of application flow / what we need at each component shortly.

**Comment by liadove** [comment]
We can store a state of the component in the component itself, this is what I was thinking too. But would it be helpful for users if they clicked on another tab by mistake have everything they already filled out?

**Comment by SomeMoosery** [comment]
I think this should rely more on data caching or user sessions than on Redux, though

**Pull request closed without merging**
