### PR TITLE
#318 disable severity buttons unless the symptom is checked

### LINKED ISSUE #318: Disable minimal/moderate/severe before checked
## Summary

We should add the functionality to disable the buttons indicating minimal/moderate/severe on the survey, unless the checkbox is clicked. We already aren't able to change this if it's not. I suggest greying / de-highlighting the boxes until checkbox is checked.

## Motivation

It may be confusing for the user if we don't implement this.

## Describe alternatives you've considered

- Allowing boxes to always be clickable
- Not doing anything

### PR DESCRIPTION
**Pull request by Avidness**
Simply checks the symptom checkbox to determine whether the severity buttons should be disabled or not.

fixes #318

### CODE REVIEW

**Comment by SomeMoosery** [comment]
Awesome! If you get the chance, could you bump the version in `package.json`? I know this is very minor but I want to start holding stricter to that just in case we need to troubleshoot later on.

**Comment by Avidness** [comment]
No worries, will do :+1:

**Comment by Avidness** [comment]
@SomeMoosery Should be good to merge now

**Comment by SomeMoosery** [comment]
Great, thanks Alan!

**Pull request merged**
