### PR TITLE
fix onboard style

### LINKED ISSUE #505: Remove profile photo option from onboarding
## Summary

- [ ] Remove the blank avatar from onboarding screen

## Motivation

Right now, we don't have the ability to add a profile photo, and it's not in our nearterm goals, so we can remove it and re-implement it when we need it. It may confuse users for now.

### LINKED ISSUE #507: Make onboarding text boxes choice boxes highlight similarly to survey
## Summary

- [ ] Use styling similar to survey to have only one box out of the choice boxes (such as male / female) stay highlighted

Screen Shot 2020-04-15 at 1 14 53 AM

## Motivation

We want to have a cohesive UI/UX for the end user

### LINKED ISSUE #508: Stylize address bar in onboarding to allow for full address to show
## Summary

- [ ] reorganize onboarding text inputs in order to better fit most addresses. Currently, anything aside from very short cities will be cut off.

Screen Shot 2020-04-15 at 1 14 53 AM

## Motivation

We want a clean UX for the user - even though this is minor, it will make a difference in the users' eyes.

### PR DESCRIPTION
**Pull request by AdhamAH**
## IMPORTANT: Please do not create a Pull Request without creating an issue first.

**Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.**

**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes** 

fixes #508 fixes #507 fixes #505

### Test plan (required)

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.
1- delete profile image `OnboardUser.jsx`
2- changed the style of buttons when selected `OnboardUser.jsx`
3- Make every address in its own line `OnboardUser.jsx`
4- override List background-colour `Layout.jsx`
5- deleted unused `location.js` file

Screenshot 2020-04-15 at 11 45 40
Screenshot 2020-04-15 at 11 45 54

### Final Checklist

- [x] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
- [ ] Have you added any new tests necessary?
- [x] Is your PR rebased off the most current master?
- [x] Have you squashed all commits, or if you will merge will you squash all commits?
- [x] Did you use yarn, not npm?
- [x] Did you use Material-UI wherever possible?
- [x] Did you format according to Prettier?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by AdhamAH** [comment]
I didn't make the colour of the text buttons as in the survey 'black' but 'gray'
I think it looks cleaner and better than the black and I think we should change that with the survey too
see the deference 
Screenshot 2020-04-15 at 12 33 28

Screenshot 2020-04-15 at 12 29 58



If you want I can make the changes in this PR

**Comment by SomeMoosery** [comment]
My worry is that may be harder to read if the user is in bright sunlight or something. I'd vote to leave everything as black to stay consistent not just in buttons but in text colors across the app, and we can consult @BrianHHough and see what he thinks, and then make another issue for changing the font colors all at once.

**Comment by AdhamAH** [comment]
Ok, back to black 🤘🏼😁

**Comment by SomeMoosery** [comment]
Great! Looks like since Pavel's changes just merged in you just need a quick rebase off of master to handle the merge conflict in `OnboardUser` - sorry about that!

**Pull request merged**
