### PR TITLE
fix: changed soarThroat to soreThroat to get rid of error

### PR DESCRIPTION
**Pull request by Ahwan0717**
Was getting a bug from SymptomsTracker.js so this fix resolves it!
Screen Shot 2020-03-23 at 1 19 02 PM

### CODE REVIEW

**Comment by friedger** [comment]
The PR description does not reflect the changes made. It is difficult to review.

**Comment by Ahwan0717** [comment]
Ah sorry, let me fix it up so it's easier to review.

**Comment by pavel-ilin** [comment]
It's my bad, I can fix it right now

**Comment by Ahwan0717** [comment]
Just changed lines 72 and 122 @friedger. Not sure why it's recording more insertions and deletions for me. It is the same as before other than that though. But removed a dummy component I had so changes are a bit easier to see. And no worries @pavel-ilin

**Comment by SomeMoosery** [comment]
Need to rebase off master now as well

**Comment by Ahwan0717** [comment]
rebased and fixed merge conflict.

**Comment by SomeMoosery** [comment]
I might be missing something but now I'm looking at the `Files Changed` tab here and I'm not seeing any changes made with this PR?

**Comment by SomeMoosery** [comment]
I think this can be closed as these changes already appear in master

**Pull request closed without merging**
