### PR TITLE
Redirect to survey

### PR DESCRIPTION
**Pull request by liadove**
fixes https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/215
when the user submits a survey it will redirect to log tab

### CODE REVIEW

**Comment by SomeMoosery** [comment]
I'm a bit confused with what this issue is solving. Could you rebase off current master so that only necessary changes are included in the PR? As well as update the body of the PR with syntax "fixes #<ISSUE>" and a more detailed description or screenshots/gifs of what this PR is resolving (for example, you're mentioning this fixes #204 which is already closed).

**Comment by liadove** [comment]
For redirecting to the survey when user login we needed to know if the survey was submitted. For that, I needed to put everything in redux, to save the answers. And that's why i thought it was related to the closed issue https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/204 when we wanted to control our inputs with redux. 
So now when you click save my responses it will save them. That's how it will indicate if the user took the survey. and redirect to log tab if didn't. 
Screen Recording 2020-03-27 at 12 50 33 PM

**Comment by SomeMoosery** [comment]
Sounds good, I think that makes sense. I'll still need the body of the original PR changes to the appropriate keyword to close the related issue, as well as a rebase off of the current master so that only appropriate files are updated 👍

**Comment by SomeMoosery** [comment]
I think this looks good, although it becomes difficult to deduce what's actually being updated and what is extraneous when you update styling. If possible, please try to remove as it's difficult to figure out what exactly is changing and what's just being formatted differently when there's 21 files changed. 

Looks like a test is failing as well, I'm having trouble opening the Travis build, but you can run `npm run test` to see where it failed.

And please add "fixes #<ISSUE>" somewhere in your original PR body so that the ticket will automatically close.

**Comment by liadove** [comment]
Sorry about that! I'll make separate PR for each issue. Next time will do it clearer.

**Pull request closed without merging**
