### PR TITLE
Update travis.yml to run separate commands

### LINKED ISSUE #692: [BUG] Incorrectly formatted travis.yml file
# ⚠️ IMPORTANT: Please fill out this template to give us as much information as possible to address the issue.

### Prerequisites

- [x] check this box if you have completed the following:
    - Reproduced the problem in QA
    - Reviewed the [contributing guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md) and [support](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) files
    - Reviewed the README file for the repository you are working in
    - Searched for relevant instructions [on our Discord server](https://discord.gg/pPERUuv)
    - Searched the issues of the repository you are working in to make sure one was not already filed

### Description of the Bug/Issue

During the TravisCI build I noticed some commands that were not running correctly in the logs. Sometimes the features will still build successfully, but there is some cleanup to do here.

### Steps to Reproduce

1. Push a commit
2. View TravisCI build logs
3. See errors below

### Expected Behavior

I expected the commands listed in travis.yml to run sequentially.

### Actual Behavior

Based on the config here:

```yaml
language: node_js

node_js:
  "stable"
  
cache:
  directories:
   node_modules

before_install:
  npm -g install yarn
  npm install -g jest-dom
  npm install -g react-scripts
  cd client
  yarn
  
before_script:
  cd client
  yarn

script:
  yarn test
  yarn run build
```

The commands are lumped together, see:

```bash
$ npm -g install yarn npm install -g jest-dom npm install -g react-scripts cd client yarn
$ cd client yarn
$ yarn test yarn run build
```
and 
```bash
Ran all test suites matching /yarn|run|build/i.
The command "yarn test yarn run build" exited with 0.
```

### Reproduces How Often

100% (can be seen in both [failed](https://travis-ci.org/github/COVID-19-electronic-health-system/Corona-tracker/builds/683881624) and [passing](https://travis-ci.org/github/COVID-19-electronic-health-system/Corona-tracker/builds/683638470) entries)

### Additional Information

I will submit a PR following this issue with my proposed changes based on the [Travis CI documentation](https://docs.travis-ci.com/user/job-lifecycle/).

### PR DESCRIPTION
**Pull request by whoabuddy**
# ⚠️ __IMPORTANT: Please do not create a Pull Request without creating an Issue first.__

All changes need to be discussed before proceeding. Failure to do so may result in the pull request being rejected.

Before submitting a pull request, please be sure to review:
- Our Code of Conduct: https://github.com/COVID-19-electronic-health-system/.github/blob/master/CODE_OF_CONDUCT.md
- Our Contributing Guidelines: https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md
- Our Support documentation: https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md

-----

## Please include the issue number the pull request fixes by replacing YOUR-ISSUE-HERE in the text below.

Fixes #692

## Summary

This pull request updates the formatting of the travis.yml file to ensure each command is run individually.

## Details

I am not a Travis CI pro so a thorough review is appreciated, but from the way I understand it, the changes to this file should fix the build process.

## Test Plan (required)

Creating the PR to see if it affects the Travis CI build, otherwise I will need help for the best way to test/deploy this.

## Final Checklist

- **n/a?** For CoronaTracker, did you bump the version in `package.json`?
    - Update the second decimal for a major change
    - Update the third decimal for a minor change
    - Numbers can go past 9, e.g. `1.0.9` => `1.0.10`
    - For more info, read about [Semantic Versioning](https://semver.org/)
- **n/a?** Did you add any new tests as necessary?
- [x] Is your PR rebased off the most current master?
- [x] Have you squashed all commits? _(can be done at merge)_
- [x] Did you use `yarn` not `npm`? _(important!)_
- [x] Did you use Material-UI wherever possible?
- [x] Did you run `yarn lint` on the code?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by whoabuddy** [comment]
This appears to have solved the problem of the commands running separately, however I am still getting some build errors that I saw when trying to build locally as well.

Yarn has some trouble with the dependency `canvas`:
```
error /home/travis/build/COVID-19-electronic-health-system/Corona-tracker/client/node_modules/canvas: Command failed.
Exit code: 1
Command: node-pre-gyp install --fallback-to-build
Arguments: 
Directory: /home/travis/build/COVID-19-electronic-health-system/Corona-tracker/client/node_modules/canvas
```
and
```
node-pre-gyp http GET https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v83-linux-glibc-x64.tar.gz
node-pre-gyp http 404 https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v83-linux-glibc-x64.tar.gz
node-pre-gyp WARN Tried to download(404): https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v83-linux-glibc-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for canvas@2.6.1 and node@14.2.0 (node-v83 ABI, glibc) (falling back to source compile with node-gyp) 
node-pre-gyp http 404 status code downloading tarball https://github.com/node-gfx/node-canvas-prebuilt/releases/download/v2.6.1/canvas-v2.6.1-node-v83-linux-glibc-x64.tar.gz 
```

Yarn also had trouble with `pangocairo` via `pkg-config`:
```
Package pangocairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `pangocairo.pc'
to the PKG_CONFIG_PATH environment variable
```

I'm not sure how to fix this on Travis CI, but on my local machine (Linux Mint / Ubuntu-based), I ran the following, and afterward the errors above were gone:

```bash
sudo apt-get install libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
```

Hopefully that helps!

**Comment by SomeMoosery** [comment]
I'm just a bit confused - is this fixing any tests / pipeline stuff? Or is this more of a cosmetic change. Either way it looks good, but I want to be sure

**Comment by whoabuddy** [comment]
Yes, this fixes how Travis CI runs the commands, which currently are getting bunched together based on syntax.

Regarding the dependency issues in Ubuntu, there is [an article here](https://docs.travis-ci.com/user/installing-dependencies/) that outlines how to fix it, and I'm testing that out now as part of this PR.

This is more of an overall change versus something specific to what caused the build to fail, but I think it will lead to a more consistent experience with the testing. If you look at the output in my initial issue you can see how things weren't running 100% correctly based on the commands provided versus the console output.

**Comment by whoabuddy** [comment]
Ok, so not sure what happened on the last Travis CI check as the logs are null, but I got it back to passing status. Here's a more detailed version of what I fixed now that I know the fix worked!

1. The Travis CI setup relies on Ubuntu, which requires a few extra dependencies before it can successfully build the project. Those are listed in the first post above and in the final config file.
2. The Travis CI YAML file was not recognizing commands as separate commands, and rather stringing them together. For example:

```
before_install:
  npm -g install yarn
  npm install -g jest-dom
  npm install -g react-scripts
```

Was actually being run as:

```
npm -g install yarn npm install -g jest-dom npm install -g react-scripts
```

There are two ways to fix this, one is to use && at the end of each line, so the result is:

```
npm -g install yarn && npm install -g jest-dom && npm install -g react-scripts
```

But that gets hard to debug in the long run, so instead we can use a hyphen `-` to separate the commands, like this:

```
before_install:
  - npm -g install yarn
  - npm install -g jest-dom
  - npm install -g react-scripts
```

So when they run in Travis CI, the result is:

```
npm -g install yarn
npm install -g jest-dom
npm install -g react-scripts
```

In addition to that, several packages are required in order to build the app on Ubuntu, which is now taken care of as part of the `before_install` procedure using the two lines below:

```
before_install:
  - sudo apt-get update
  - sudo apt-get -y install build-essential cmake libcairo2-dev libpango1.0-dev libssl-dev	  - sudo apt-get -y install build-essential cmake libcairo2-dev libpango1.0-dev libssl-dev libjpeg-dev libgif-dev librsvg2-dev
```

I also added `npm install -g canvas` since that was required on my system, and part of what requires the additional packages above in order to build.

Everything passed this time around, so this should help others efficiently test everything and make sure the errors we see are real errors! :upside_down_face: :heavy_check_mark:

**Comment by SomeMoosery** [comment]
Sounds good! Just needs 1 more approval

**Pull request merged**
