### PR TITLE
deleted unused CSS and transfer to Material-UI style

### LINKED ISSUE #282: Text Logo Misaligned on Disclaimer on Mobile
### Prerequisites

* [ ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

When viewing the disclaimer on mobile, the text logo is off center and requires scrolling to view the entire disclaimer.

Screen Shot 2020-03-28 at 2 12 06 PM

### Steps to Reproduce

1. Inspect on mobile view
2. Log in

**Expected behavior:**

The text logo should be centered and fully visible within the disclaimer.

**Actual behavior:**

The text logo is off-center and too large for the screen.

**Reproduces how often:**

100%

### LINKED ISSUE #297: Loding components
## Idea

1- Remove the loading ball from `Login.js` to a separate component  `Loading.js`
2- Add the component to `index.js` in place of `<h1>Loading...</h1>`
3- restyle the ball 
4- delete `Login.css` and style `login.js` using Material-UI

ezgif com-video-to-gif

## this is done

### PR DESCRIPTION
**Pull request by AdhamAH**
fixes #282 
fixes #297

## issue
I will be making the transfer of components fully to Material-UI and this is the first stage

## Motivation 
To follow the development plan and only use Material-UI for styling and making components

### CODE REVIEW

**Comment by SomeMoosery** [comment]
This looks good so far! Could you make a PR to encapsulate the work being done here as well? You say this PR is the first stage, maybe the issue should list out all stages of the transition to full Material-UI

Also, should I leave this PR open for now while you continue to work through this? Or should we do it as multiple different PRs?

**Comment by AdhamAH** [comment]
It failed. I will close it and make a one with all the changes if that's better. @SomeMoosery

**Comment by SomeMoosery** [comment]
No need - you can leave this open. The test failing doesn't have to do with this PR, it's actually something I'm working on now! If you want to just push all changes to this PR that should be fine 👍

**Comment by AdhamAH** [comment]
will do, so every time I need to fetch, merge and rebase after that push and all will be good?

**Comment by SomeMoosery** [comment]
This looks great @AdhamAH - thank you so much for a much-needed overhaul of the styling!

**Pull request merged**
