### PR TITLE
Gave classes.buttons in More component a minHeight of 50px to fix tex…

### LINKED ISSUE #462: Bug in More component, singout button text
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description
When the keyboard pop up the size becomes very small and the yet get out of the button 

bug

### Steps to Reproduce

1. 
2. 
3. 

**Expected behavior:**
text inside the button

**Actual behavior:**
text outside

**Reproduces how often:**
100% when small size applied 

### Versions
0.3.16

### Additional Information
none

### PR DESCRIPTION
**Pull request by mamutahr**
…t overflowing buttons

## IMPORTANT: Please do not create a Pull Request without creating an issue first.

**Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.**

**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes** 

fixes #462 

### Please provide enough information so that others can review your pull request:

Added a minHeight of 50px

### Explain the **details** for making this change. What existing problem does the pull request solve?

 to fix text overflow in signout button in the more component

### Test plan (required)

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Works on both desktop:

image

And on Android chrome(white spot is the keyboard, phones screenshot is a bit messed up):
image

### Final Checklist

- [x] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
- [ ] Have you added any new tests necessary?
- [x] Is your PR rebased off the most current master?
- [ ] Have you squashed all commits, or if you will merge will you squash all commits?
- [x] Did you use yarn, not npm?
- [x] Did you use Material-UI wherever possible?
- [ ] Did you format according to Prettier?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by mamutahr** [comment]
Hello, im a little new to this since its my first PR shoud I make a new request for these changes especially for the change in the package.json?

**Comment by acthelemann** [comment]
> Hello, im a little new to this since its my first PR shoud I make a new request for these changes especially for the change in the package.json?

@mamutahr No, you should make your changes to this PR.

For the `package.json` change, make another commit on your branch and push it, this PR will automatically update with your new commit.

For the other three changes, go to the first comment on this PR that you made and click the three dots (...) to **Edit** the comment. There you can add more information.

Let me know if you have any questions or need help!

**Comment by SomeMoosery** [comment]
Looks good other than the changes @acthelemann suggested

**Comment by mamutahr** [comment]
@acthelemann  changed, thank you!

**Pull request merged**
