### PR TITLE
ShareButtons component

### LINKED ISSUE #433: Implementing Share Buttons in app and on website
## Summary

Either www.sharethis.com or a bit of JavaScript to enable easy sharing / pre-drafted social posts that auto-populate in social channels (Twitter, Facebook, LinkedIn) and help to amplify our app to other people so they can share this on social.

## Motivation

To help make our app more viral/marketable.

## Describe alternatives you've considered

www.sharethis.com or Javascript code

## Additional context

make buttons with pre-drafted posts so its easy for users to share the app/their experience directly to social media/online!

### PR DESCRIPTION
**Pull request by pavel-ilin**
fixes #433 

### Please provide enough information so that others can review your pull request:

- Create ShareButtons component with [react-share](https://github.com/nygardk/react-share#readme) library
- Create basic test for ShareButtons component

@BrianHHough We going to need to add template of the message for share and hashtags for some of the social networks. More social networks can be added if needed.

@AdhamAH We need to make a decision where to place this component.

### Test plan (required)

yarn test

### Final Checklist

- [x] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
- [x] Have you added any new tests necessary?
- [x] Is your PR rebased off the most current master?
- [x] Have you squashed all commits, or if you will merge will you squash all commits?
- [x] Did you use yarn, not npm?
- [x] Did you use Material-UI wherever possible?
- [x] Did you format according to Prettier?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by SomeMoosery** [comment]
You're on a roll @pavel-ilin!!

We'll look for where to best add this into the full app (legal pending 🤞) soon

**Comment by AdhamAH** [comment]
From the code (I didn't test) we can add this to drop menu component that wrapped inside an icon. And then we can place it wherever we want. That's what I am thinking.

**Comment by SomeMoosery** [comment]
I agree, but let's hold off on adding it anywhere for now, just because links to third-party outside websites can add some legal complexity to this :/

**Comment by AdhamAH** [comment]
Exactly!! thanks to the speedy delivery from @pavel-ilin also, we only need to worry about making that component

**Pull request merged**
