### PR TITLE
russian translation

### PR DESCRIPTION
**Pull request by liadove**
fixes https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/308

### CODE REVIEW

**Comment by akilhylton** [comment]
I had a caching issue where it would sometimes randomly not display the disclaimer text. Curious if you ran into this issue and if so how were you able to solve it? @liadove

**Comment by liadove** [comment]
@akilhylton I didn't run into this issue. When does it happen? Could you write an issue for it?

**Comment by SomeMoosery** [comment]
Need rebase

**Comment by SomeMoosery** [comment]
Merging for now, can edit and undo any high-ranking changes later

**Pull request merged**
