### PR TITLE
Reversed map ordering of flashcards to reflect numbering

### LINKED ISSUE #577: Flashcards go from #15 -> #1, not vice versa
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Currently, the numbered flashcards go in reverse order

**Expected behavior:**

Flashcards go from 1 to 15

**Actual behavior:**

Flashcards go from 15 to 1

**Reproduces how often:**

100%

### Versions

1.0.1

### PR DESCRIPTION
**Pull request by mamutahr**
## IMPORTANT: Please do not create a Pull Request without creating an issue first.

**Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.**

**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes** 

fixes #577 

### Please provide enough information so that others can review your pull request:

image
Changed data={cardData[cardData.length - i - 1]} to data={cardData[i]} in FlashCards component

Also fixed fact numbers in fakeCardData.js

### Explain the **details** for making this change. What existing problem does the pull request solve?

Flashcards would show up in reverse order starting with fact 15 and going to fact 1

fakeCardData went 1,2,6,7,8,8 ... just fixed the numbering

### Test plan (required)

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

flashcards

### Final Checklist

- [x] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
- [ ] Have you added any new tests necessary?
- [x] Is your PR rebased off the most current master?
- [x] Have you squashed all commits, or if you will merge will you squash all commits?
- [x] Did you use yarn, not npm?
- [x] Did you use Material-UI wherever possible?
- [x] Did you format according to Prettier?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by SomeMoosery** [comment]
Can you add a photo/gif of the code working in the UI, not the code itself :)

**Comment by mamutahr** [comment]
Oops, sorry I thought the gyazo gif would show up automatically

**Comment by SomeMoosery** [comment]
I know you mentioned this, but would you be able update the flashcard numbers in `fakeCardData.js`? I'm not sure why this happened, but we should change this for now. Also, rebase off current master / bump `package.json` since new PRs have merged in since opening this 👍

**Comment by mamutahr** [comment]
Will do!

**Comment by mamutahr** [comment]
I messed up git a little on my end and had to undo a commit and then push the new changes. The new commit shows up on my repo but here it still says only 2 files changed when it should be 3, does this mean its messed up?

**Pull request merged**
