### PR TITLE
ToggleInfo.js sub-component - closes Issue #23

### PR DESCRIPTION
**Pull request by johnemurphy1**
This is the DiagnosticContainer ToggleInfo (button) sub-component.  It will toggle between the Temperature and Symptoms. Fixes #<23>issue

### CODE REVIEW

**Comment by AdhamAH** [comment]
this was here for a long time with no rebase to be able to merge.
@SomeMoosery is this still needed? I think it is not but not sure.

**Comment by SomeMoosery** [comment]
Good catch @AdhamAH  - @johnemurphy1 are you still working on this? It may be a pain to refactor at this point since this has been sitting out for so long, I'd maybe suggest closing / opening a new PR with the changes - what do you think @johnemurphy1 ?

**Comment by johnemurphy1** [comment]
@pavel-ilin and I worked on this and created the PR over a week ago. We used code from issue #137 (Fact/Quiz interactive mode) and refactored. It went into review and then was pushed back into in progress. If you think it's not needed now, we can close it. However, if it just needs to be updated to use the Airbnb style, I can get that done in the next day or so and do another pull request.  Please let me know.

**Comment by SomeMoosery** [comment]
I think this PR had some merge conflicts initially so wasn't able to be merged - I think with a rebase off the most recent master (@tesla809 has added some great great documentation on that) that only the changes you made will be in this PR and it'll be able to merge, and your codebase will have the new pre-commit hook that'll run the linter (stylize it automatically where it can and alert you to where you'd have to make changes). 

Although, I'd definitely try rebasing first, but there may be a lot of merge conflicts to resolve. It's up to you if you want to resolve them, but if you didn't make that many changes to the code yourself it may be worth closing this PR and making these changes again on a new branch (not the _best_ practice and understandably a pain, but it's really just a lesser-of-two evils because there may be a lot of merge conflicts to resolve).

**Comment by johnemurphy1** [comment]
just tried this again...having some issues with GitHub...see screen shot 
image

**Comment by AdhamAH** [comment]
@johnemurphy1 I think you are pushing to the master of the main repository which you don't have access to, I am not sure.
In any case, I advise you to follow [this](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/CONTRIBUTING.md) it helped me, it could help you too.

**Comment by tesla809** [comment]
SSH key issue fixed. Helped update your origin and upstream paths. We can close this and open a new PR with the code using a feature branch like feature/toggle-button or something like that.

**Pull request closed without merging**
