### PR TITLE
Added redux to disclaimer modal

### LINKED ISSUE #200: Fix / Implement setModalHidden
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

We currently have a function `setModalHidden` in [`Disclaimer.js`](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/d48068321ddfad6eb7d7e3b855df06a00c1d3b32/client/src/components/Disclaimer.js#L22) that causes our program to error out on startup as it's not implemented anywhere.

We should implement this functionality so that disclaimer behaves properly, or remove it entirely for the time being.

### Steps to Reproduce

1. Start up application

**Expected behavior:**

The application runs

**Actual behavior:**

The application errors out

**Reproduces how often:**

100%

### PR DESCRIPTION
**Pull request by Tanvez**
fixes #200
Still need to add some CSS styling to make it look nice and fix the mobile view. 
Animated GIF-downsized

### CODE REVIEW

**Comment by SomeMoosery** [comment]
Looks great @Tanvez - super clean! Would you want me to leave this open/marked as WIP until you get the styling done?

**Comment by Tanvez** [comment]
Yea sounds good! Will let you know when the styling is done.

**Comment by Tanvez** [comment]
Updated the CSS for the Disclaimer modal. Let me know if i should change anything.
Screen Shot 2020-03-26 at 6 09 07 PM
Screen Shot 2020-03-26 at 6 07 37 PM
Screen Shot 2020-03-26 at 6 07 30 PM
Screen Shot 2020-03-26 at 6 06 55 PM

**Comment by SomeMoosery** [comment]
Awesome!

**Pull request merged**
