### PR TITLE
Always start at top of page

### LINKED ISSUE #441: Always start at top of page on mobile
## Summary

- [ ] when navigating between pages/tabs/etc, ensure the window is always scrolled to the top

## Motivation

If the user is taking a survey, and on page 2 scrolls down to click continue, we don't want their browser to remain scrolled down on page 3 - we want them to start at the top. This will improve UX

### PR DESCRIPTION
**Pull request by gdemu13**
when navigating between pages/tabs/etc, the window scrolls to the top

## IMPORTANT: Please do not create a Pull Request without creating an issue first.

**Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.**

**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes** 

fixes #441 

### Explain the **details** for making this change. What existing problem does the pull request solve?

The page scrolls to top when user changes survey page. Couldn't find same issue on any other page.

### Test plan (required)
change pages of the survey.

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

### Final Checklist

- [x] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
- [ ] Have you added any new tests necessary?
- [x] Is your PR rebased off the most current master?
- [ ] Have you squashed all commits, or if you will merge will you squash all commits?
- [x] Did you use yarn, not npm?
- [x] Did you use Material-UI wherever possible?
- [x] Did you format according to Prettier?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by SomeMoosery** [comment]
Looks great! Could you just bump the version in `/client/package.json` - then this is good to merge in!

**Comment by AdhamAH** [comment]
This looks great, thanks for your first contribution!
I must say though that this should have been applied to all pages not only the surveys.
@SomeMoosery should we open a new issue or reopen the old one? And if @gdemu13 has the time and would like to take assigning him?

**Comment by gdemu13** [comment]
thanks @AdhamAH ! Sorry, I didn't notice this issue on other pages earlier. If you make new issue please assign it to me and will try to do it tomorrow.

**Comment by SomeMoosery** [comment]
Ah, good point - I didn't catch that.

I'll open up a new issue and assign you @gdemu13

**Comment by AdhamAH** [comment]
No problem at all! thanks for stepping up again! @gdemu13

**Pull request merged**
