### PR TITLE
fixed onboard textinputs

### LINKED ISSUE #589: Differentiate UI between button and input fields
## Summary

- [ ] In onboarding section, and anywhere else with text inputs, make it more obvious that these are text input fields, and not buttons. For instance, don't say "click here."
- [ ] Change Age input to only accept numbers

## Motivation

User and professional reviews are telling us buttons and text inputs look too similar

### PR DESCRIPTION
**Pull request by PhurbaSherpa**
## IMPORTANT: Please do not create a Pull Request without creating an issue first.

**Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.**

**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes** 

fixes #589 

### Explain the **details** for making this change. What existing problem does the pull request solve?
Was hard to tell if a field was a dropdown or a text input. Changed styling for inputs to be different from UI buttons. Made Placeholder for text input to say "Enter Age" etc. Made Age input a number input. 

### Test plan (required)
Go to Onboard page to see view.
1. Click More
2. Click Update Information

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Screen Shot 2020-04-20 at 1 57 53 PM

### Final Checklist

- [x] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
- [ ] Have you added any new tests necessary?
- [x] Is your PR rebased off the most current master?
- [x] Have you squashed all commits, or if you will merge will you squash all commits?
- [x] Did you use yarn, not npm?
- [x] Did you use Material-UI wherever possible?
- [x] Did you format according to Prettier?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by SomeMoosery** [comment]
Will also need a bump up to 1.0.6 as another PR just merged in 👍

**Comment by SomeMoosery** [comment]
It looks like these last pushes pulled Crispina's changes into your PR - perhaps be sure you're rebased off the most current master? I'm not sure if that's the fix though

**Comment by PhurbaSherpa** [comment]
> It looks like these last pushes pulled Crispina's changes into your PR - perhaps be sure you're rebased off the most current master? I'm not sure if that's the fix though

Yeah when I do git status it says that I my branch has diverged. I am new to these git commands so I'm not too sure what to do.

**Comment by acthelemann** [comment]
You git history might be messy and this won't work, but is should be something like this:

Get latest changes

```sh
git fetch --all
```

Update your local `master`

```sh
git checkout master 
git pull upstream master
```

Rebase your changes onto the most up to date `master`

```
git checkout onboardTextInputs
git rebase master
```

**Comment by PhurbaSherpa** [comment]
> looks good!
> I think he should squash them before pushing


> git checkout onboardTextInputs
> git rebase master

yeah my git history might be messy, it says I'm up to date but that my branch has diverged from origin/onboardTextInputs

**Comment by acthelemann** [comment]
Hmm maybe a `git push - f origin onboardTextInputs`

**Comment by PhurbaSherpa** [comment]
> Hmm maybe a `git push -f origin onboardTextInputs`


> Hmm maybe a `git push -f origin onboardTextInputs`

It seems to have fixed it.

**Comment by SomeMoosery** [comment]
Just needs another `package.json` bump and then it looks good to go to me

**Comment by acthelemann** [comment]
https://learngitbranching.js.org/

^ Pretty useful site if you have some time.

**Comment by PhurbaSherpa** [comment]
> https://learngitbranching.js.org/
> 
> ^ Pretty useful site if you have some time.
Will definitely look at it. Thanks!

**Pull request merged**
