### PR TITLE
Added v1-final-MVP-subcomponents for issue #61

### PR DESCRIPTION
**Pull request by Tanvez**
Note: I didn't include the login screen and the quiz screens because I didn't think they needed subcomponents. Let me know if I should change anything.
Issue Reference #61

### CODE REVIEW

**Comment by SomeMoosery** [comment]
Would you be able to attach screenshots? I'm sure they look great - just want to be sure we have some context!

**Comment by SomeMoosery** [comment]
Hey sorry, I wasn't clear in my last message! When you add in `.png`s to a PR, I'm not able to view them - I can just see that they're added. Sorry to make you repeat/undo work, but if you remove the screenshots you added in your last commit (and either add them in a comment here or not, I'm sure they're great!) I'll go ahead and merge this 👍

**Comment by Tanvez** [comment]
ok i undid the add of the extra duplicate screen shots.

survey-view-slider
image

survey-view-grouped-buttons
image

survey-view-check-grouped-buttons-view
image

CORONATRACKER UI - Logged In Home Page - Patient Daily Temp Graph
image

CORONATRACKER UI - Logged In Home Page - Patient Daily Checkin
image

CORONATRACKER UI - Logged In Home Page - Patient Daily Bell notification
image

CORONATRACKER UI - Logged In Home Page - Patient Calendar Tracking
image

**Comment by SomeMoosery** [comment]
Thanks @Tanvez !!

**Pull request merged**
