### PR TITLE
Change main view on large screens 

### LINKED ISSUE #485: Change health log view on large screens
## Summary
The calendar looks wired and big on a large screen 

## Motivation
Make it look better in my opinion 
Screenshot 2020-04-13 at 14 13 18

## Describe alternatives you've considered
leaving it  as it is

### PR DESCRIPTION
**Pull request by AdhamAH**
## IMPORTANT: Please do not create a Pull Request without creating an issue first.

**Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.**

**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes** 

fixes #485 

### Test plan (required)

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

Screenshot 2020-04-13 at 16 12 43

### Final Checklist

- [x] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
- [ ] Have you added any new tests necessary?
- [x] Is your PR rebased off the most current master?
- [ ] Have you squashed all commits, or if you will merge will you squash all commits?
- [x] Did you use yarn, not npm?
- [x] Did you use Material-UI wherever possible?
- [x] Did you format according to Prettier?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by SomeMoosery** [comment]
Looks so much cleaner! I'll merge when tests pass

**Comment by AdhamAH** [comment]
@SomeMoosery  this is the second time this happens with me. It is the snapshot file

**Comment by SomeMoosery** [comment]
Hmm, try deleting the snapshot and running tests again?

**Comment by AdhamAH** [comment]
actually you need to run the test and when it fails you press `u`, run again and voila!

**Comment by AdhamAH** [comment]
BTW, I deleted the snapshot but it didn't work

**Comment by SomeMoosery** [comment]
Ah okay! Makes sense then, thanks Adham 👍

**Pull request merged**
