### PR TITLE
Feat/survey stepper

### PR DESCRIPTION
**Pull request by liadove**
## IMPORTANT: Please do not create a Pull Request without creating an issue first.

**Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.**

**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes** 

fixes https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues/391

### Test plan (required)

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

image

### Final Checklist

- [x] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
- [ ] Have you added any new tests necessary?
- [x] Is your PR rebased off the most current master?
- [x] Have you squashed all commits, or if you will merge will you squash all commits?
- [x] Did you use yarn, not npm?
- [x] Did you use Material-UI wherever possible?
- [x] Did you format according to Prettier?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by AdhamAH** [comment]
When you rebase to the master you will find that there is a new fourth survey now.
I am not sure if should be added or not @SomeMoosery

**Comment by liadove** [comment]
Thanks! @AdhamAH I just rebased and made some changes with the step 4

**Comment by AdhamAH** [comment]
@liadove Nice work! Thanks for cleaning the warnings

**Comment by AdhamAH** [comment]
That's why we need two reviews for each PR, so if some lazy eyes like me miss something more sharped ones will catch it. Though it is 2:25 AM 😁

**Comment by liadove** [comment]
@acthelemann I have a bunch of eslint errors when I commit with new changes. I guess because they weren't used. Do you know what I can do to avoid errors?

**Comment by acthelemann** [comment]
@liadove I was thinking actually deleting the lines, not just uncommenting them.

**Comment by AdhamAH** [comment]
they will be used later, I think it is easier they way she made them

**Comment by acthelemann** [comment]
Sounds good

**Comment by liadove** [comment]
@acthelemann @AdhamAH Thanks for reviewing, I will leave it as it is

**Comment by AdhamAH** [comment]
Then I will merge and if needed I can delete them in my PR as I need to rebase any way @acthelemann @liadove

**Pull request merged**
