### PR TITLE
Survey page 1 style updates (#423)

### LINKED ISSUE #423: Make emojis on survey larger, number line
## Summary

- [x] emojis displayed during the survey are larger 
- [x] we have intermittent numbers on the number line for sliders on survey (1.5, 2.5, etc...)

## Motivation

We want this to be as intuitive and simple for the user, leaving them with little room left to guess on what they're to do or what things mean.

### PR DESCRIPTION
**Pull request by acthelemann**
## IMPORTANT: Please do not create a Pull Request without creating an issue first.

**Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.**

**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes** 

Fixes #423

### Explain the **details** for making this change. What existing problem does the pull request solve?

Make emojis larger, add intermittent numbers on sliders, improve desktop styling. Also, have value label above sliders be always visible to be more similar to the wireframe.

### Test plan (required)

Demonstrate the code is solid. Example: The exact commands you ran and their output, screenshots / videos if the pull request changes UI.

**iPhone X survey page 1**

iphone-x-survey-page-1

**Desktop survey page 1**

desktop-survey-page-1

### Final Checklist

- [x] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
- [x] Have you added any new tests necessary?
- [x] Is your PR rebased off the most current master?
- [x] Have you squashed all commits, or if you will merge will you squash all commits?
- [x] Did you use yarn, not npm?
- [x] Did you use Material-UI wherever possible?
- [x] Did you format according to Prettier?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by acthelemann** [comment]
Looking into the build failures - tests didn't pass.

**Comment by SomeMoosery** [comment]
I'm sure you saw this already but looks like something with `openComment` being undefined 🤔

**Comment by acthelemann** [comment]
PR was just merged, gotta update `package.json`. One minute.

**Comment by acthelemann** [comment]
All right, we're all good.

**Pull request merged**
