### PR TITLE
updated education quiz

### LINKED ISSUE #490: On Education Quiz section should be changed to True or False (Currently "False or True")
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description
Wording on Quiz in education section is a bit clunky should be True or False 

### Steps to Reproduce

1. Navigate to Education
2. Go to Quiz Section
3. Read

**Expected behavior:**
Change wording to "True or False"

**Actual behavior:**
Currently "False or True"

**Reproduces how often:**
100%

### PR DESCRIPTION
**Pull request by Josh1794**
## IMPORTANT: Please do not create a Pull Request without creating an issue first.

**Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.**

**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes** 

fixes #490 

### Please provide enough information so that others can review your pull request:
Changed wording of quiz section from False or True to "True or False" and changed swiping direction and instructions to match with the wording.

### Test plan (required)
Ran through the quiz to ensure functionality was still working.

### Final Checklist

- [ ] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
**Did not deem it necessary**
- [X] Have you added any new tests necessary?
- [X] Is your PR rebased off the most current master?
- [X] Have you squashed all commits, or if you will merge will you squash all commits?
- [X] Did you use yarn, not npm?
- [X] Did you use Material-UI wherever possible?
- [X] Did you format according to Prettier?
- [X] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by Josh1794** [comment]
There was an issue with score and tracking will make new PR when fixed

**Comment by Josh1794** [comment]
NVM seems to be a local branch issue

**Comment by Josh1794** [comment]
True or False is the colloquial phrase and I wanted the swipe to line up with the order of the phrase

**Comment by SomeMoosery** [comment]
I think we can have the test say "True or False" with users understanding that swiping right (so card going off the screen to the right) is for "True," and swiping left (so the card going off the screen to the left) is for "False."

Think Tinder mechanics but for pandemic education

**Comment by Josh1794** [comment]
I can switch it back if you want currently works like this 

Screen-Recording-2020-04-13-at-5


In order to switch it back all I need to do is flip the greater than/less than sign and change the instructions

**Comment by SomeMoosery** [comment]
I think we should switch it back, Swiping left ( <-- ) for true might be confusing for some

**Comment by Josh1794** [comment]
Ok sounds good will do

**Comment by Josh1794** [comment]
Also let me know if you need someone to work on the questions (i think the one about going to the ER when u have any symptoms is wrong)

**Comment by SomeMoosery** [comment]
Looks good. In terms of education - join the Discord and reach out to @jeinson on there, he's leading education efforts

**Pull request merged**
