### PR TITLE
Static images to references updated to external storage

### LINKED ISSUE #472: Update static images to reference S3 bucket
## Summary

Image links are of this format:

`https://dg1fd6ea8poyj.cloudfront.net/images/<FILE_NAME>`

Where <FILE_NAME> is the file name found in the client/src/img directory.

Example:

https://dg1fd6ea8poyj.cloudfront.net/images/Logo_CORONATRACKER_Logo.svg

- [ ] Use S3 image links in our React app, instead of hardcoded references
- [ ] Remove references to images from our `client/src/img` directory

## Motivation

This will result in a smaller build file and potentially faster load times for www.coronatrackapp.com

## Describe alternatives you've considered

Leaving the images where they are now

### PR DESCRIPTION
**Pull request by pavel-ilin**
**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes** 

fixes #472

### Please provide enough information so that others can review your pull request:

- Created ```imgUrl.js``` utility file with base url to the images storage and paths to all images. Every path to the external image exported.
- Every image reference to the internal image was replaced to the external location

- Images in ```src/img``` are not deleted.

### Test plan (required)

- yarn start
- serf though the app

### Final Checklist

- [ ] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
- [ ] Have you added any new tests necessary?
- [ ] Is your PR rebased off the most current master?
- [ ] Have you squashed all commits, or if you will merge will you squash all commits?
- [ ] Did you use yarn, not npm?
- [ ] Did you use Material-UI wherever possible?
- [ ] Did you format according to Prettier?
- [ ] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by SomeMoosery** [comment]
LGTM - just to be sure, you went through and made sure all these images are working right :) just for a sanity check

**Comment by pavel-ilin** [comment]
Fixing  tests.

@SomeMoosery Yes, I can see all images in all versions of the app.

**Comment by pavel-ilin** [comment]
Please don't merge yet. It's seed some more work.

**Comment by pavel-ilin** [comment]
My apologies for delay! All ```.svg``` files rendering successfully now. We can merge.

**Comment by acthelemann** [comment]
Nice! Should we delete or move the files in the `img` directory?

**Comment by pavel-ilin** [comment]
> Nice! Should we delete or move the files in the `img` directory?

I tested app without ```img``` directory and all images working well without local files. I would move them from the app repo to make it lighter and I would keep them somewhere just in case (I'm not sure what the best place to store them as backup).

**Comment by SomeMoosery** [comment]
Good point - we could file another issue for that or if someone just wanted to make a quick hotfix removing `img` that should be fine

**Comment by pavel-ilin** [comment]
> Good point - we could file another issue for that or if someone just wanted to make a quick hotfix removing `img` that should be fine

I will do hotfix

**Pull request merged**
