### PR TITLE
Button group

### PR DESCRIPTION
**Pull request by Ahwan0717**
I added the symptom button group for the symptom screen. I included a hover effect, so when you hover over one of the buttons, it turns grey. Let me know if this looks okay!
Screen Shot 2020-03-21 at 7 50 21 PM
Screen Shot 2020-03-21 at 7 50 09 PM

### CODE REVIEW

**Comment by SomeMoosery** [comment]
Hey @Ahwan0717 - anything I can help with? Looks like there's merge conflicts meaning you just have to rebase your copy off of the current master! 

[A guide if you need a starting point](https://stackoverflow.com/questions/15602037/git-rebase-upstream-master-vs-git-pull-rebase-upstream-master) 

Let me know if I can be of any help!

**Comment by Ahwan0717** [comment]
Ok! Also, would you guys prefer me updating this to a toggle button group instead?

**Comment by tesla809** [comment]
You can create a separate component to as a toggle button as well! It will solve two problems.
Can you add that as a separate Pull Request?
Great job @Ahwan0717 !

**Comment by friedger** [comment]
Does it hover also on mobile devices? Any UX considerations for this effect?

**Pull request closed without merging**
