### PR TITLE
Fix tests, package management

### LINKED ISSUE #259: All tests fail due to package management
### Prerequisites

* [ X ] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

All tests are currently failing

### Steps to Reproduce

1. Clone the repo
2. `cd client && yarn install && yarn run test a`

**Expected behavior:**

Tests pass

**Actual behavior:**

Tests fail

**Reproduces how often:**

100%

### PR DESCRIPTION
**Pull request by SomeMoosery**
fixes #259 

## Changes

- Fixed the broken package management causing builds to fail
- Hopefully, fixed up tests so that Travis tests will pass

### CODE REVIEW

**Comment by tesla809** [comment]
Looks Good!

**Comment by SomeMoosery** [comment]
Need some opinions here. To get the tests passing, I had to remove the actual testing functionality from two of them, along with updating the package management system.

The `Calendar.js` test simply won't work in its current state as it's not a top-level component.

The `Chart.js` test is failing due to something with enzyme. I personally don't think that it's in the team's best interest if I spend the next hours/days fixing these tests up. 

@pavel-ilin I see you're the last person to work on `Chart.js` and wrote most of the test. Would you want to create an issue and see if you can resolve this? Just unocmment `<Chart />` and run `yarn run test a` to see where it's failing.

**Comment by tesla809** [comment]
Yea agreed. The opportunity cost of fixing this would be high. @pavel-ilin knows has some memory of how the tests were written and can debug. I can help if needed @pavel-ilin.

**Comment by pavel-ilin** [comment]
My apologies for delay with response. I guess tests issue was resolved.

**Pull request merged**
