### PR TITLE
Add CODEOWNERS

### PR DESCRIPTION
**Pull request by acthelemann**
Adds a `CODEOWNERS` file for the `/client/` directory.

### CODE REVIEW

**Comment by acthelemann** [comment]
Just added the branch protection rules, so you'll see this PR needs two approving reviewers.

Admins can merge anyway, not sure if we want to not allow that.

**Comment by SomeMoosery** [comment]
I would say let's keep admins as allowed to merge, just in case something accidentally breaks and we need to do a quick hotfix.

If it's not the case already I'd say we should just make you Adham and I admins for the time being (on mobile so hard to check myself)

**Comment by acthelemann** [comment]
Yeah, I believe owners in the organization are admins by default. We are all owners.

https://github.com/orgs/COVID-19-electronic-health-system/people?query=role%3Aowner

**Comment by acthelemann** [comment]
Any other people you think should be code owners? I'm not too familiar with other people

**Comment by SomeMoosery** [comment]
I would also vote to add @pavel-ilin for this repo, thinking in terms of who contributes most often and for the longest amount of time.

We can expand the list as we continue 👍

**Comment by AdhamAH** [comment]
I almost dropped my laptop!😅 I think I pressed by mistake the merge! I don't know what to say😂

**Comment by acthelemann** [comment]
Haha should be fine

**Pull request merged**
