### PR TITLE
Create new survey flow

### LINKED ISSUE #390: Redesign Survey Components
## Summary

- [ ] Create [Survey 1 from wireframe](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/design/wireframes/FINAL-V1-03.28/Survey%20Part%201%20of%203.png)
- [ ] Create [Survey 2 from wireframe](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/design/wireframes/FINAL-V1-03.28/Survey%20Part%202%20of%203.png)
- [ ] Create [Survey 3 from wireframe](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/design/wireframes/FINAL-V1-03.28/Survey%20Part%203%20of%203.png)
- [ ] Remove old survey
- [ ] At the end of Survey Page 3, submit observation as per current survey

### PR DESCRIPTION
**Pull request by SomeMoosery**
## IMPORTANT: Please do not create a Pull Request without creating an issue first.

**Any change needs to be discussed before proceeding. Failure to do so may result in the rejection of the pull request.**

**Do not change the following line aside from replacing YOUR-ISSUE-HERE with the issue this PR fixes** 

fixes #390 

### Explain the **details** for making this change. What existing problem does the pull request solve?

- Creates Survey wrapper with three pages to conform with wireframe
- Removes old survey functionality 
- Stylizes everything consistently with style guide 
- Disallows users from leaving blank fields in a survey 
- Utilizes Redux to keep track of survey data between components
- **out of scope**, but re-orders declarations in `Tranlsations.jsx` as it was giving my linter problems.

new-survey

Screen Shot 2020-04-05 at 11 04 18 PM

Screen Shot 2020-04-05 at 11 03 54 PM

**I'm having an issue where `openComment` does not seem to save every time we create an observation. I think it may be wise to merge this all in and then create a follow-up issue as opposed to leaving this open, as it's a big change**.

### Test plan (required)

- **Not sure if tests are implemented super properly, feel free to check** 

### Final Checklist

- [x] Have you bumped the version in `package.json`?
    - Second decimal for major change, third decimal for minor change. This can go past 10 i.e. 1.0.9 !=> 1.1.0, 1.0.9 => 1.0.10
    - [Read here for more info](https://semver.org/)
- [ ] Have you added any new tests necessary?
- [x] Is your PR rebased off the most current master?
- [x] Have you squashed all commits, or if you will merge will you squash all commits?
- [x] Did you use yarn, not npm?
- [x] Did you use Material-UI wherever possible?
- [x] Did you format according to Prettier?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by SomeMoosery** [comment]
Hm, I'll look into that - I hadn't noticed. I only added that flag because I was still working on tests (they're only all passing now because I removed a Redux test). I ideally want there to be tests for this new flow and for most new additions moving forward, but if this is too much of a slow-down I'll merge without this test with a note to return to it later, as right now we just need velocity more so than anything to get this as finished as we can by 4/10, and then we can fix it up from 4/10-4/15.

**Comment by SomeMoosery** [comment]
Ah, I realized I was being dumb / forgetting something. I had removed the `hasFever`, `hascough`, etc field in this new observation because I felt they were kind of redundant, so it was trying to convert `undefined`s to strings. I'll push up my changes in just a bit, and hopefully see what's going on with this Travis test timing out now...

**Comment by SomeMoosery** [comment]
Fixed that issue with "Show Me More" not loading, there's still some minor kinks, but I'm in the camp of merging this all in now and handling any real-use-case bugs that pop up as we continue throughout the week as opposed to continuously adding to this PR since this is a pretty major change and we should build on it / refine it as we move towards the 10th.

If nobody has any qualms I'm going to merge this in like 15-20 min

**Comment by acthelemann** [comment]
The pages look iffy on desktop (the scroll bars on page 2 lol):

survey-page-1

survey-page-2

survey-page-3

**Comment by acthelemann** [comment]
Mobile looks good though!

**Comment by SomeMoosery** [comment]
Oof I know we're going for mobile-first but yeah that's unusable. I should've looked beforehand, my bad.

I'll keep going with this for a bit longer and see if I can add some CSS to at least clean this up to be usable, and then maybe make a new ticket to make it more generally appealing on desktop.

**Comment by acthelemann** [comment]
Sounds good, I'm happy to try to clean it up once it's merged.

**Comment by AdhamAH** [comment]
I tried it many times and it looks like it is not pulling all the data form the survey to 'show me more' (Dizziness, Headache, Congestion) and comments it shows in the following survey's comment 
I am testing and not trying to solve the problem, sorry about that and I am not sure if what I am testing is maybe not the main issue.
as for the styling don't worry about it it can be done later. The code you are typing is great and it is work enough! @SomeMoosery

**Comment by acthelemann** [comment]
It looks like everything from the survey is being saved correctly except for the comments on page 3.

**Comment by SomeMoosery** [comment]
Yeah @AdhamAH I'd be sure you've pulled in the most recent changes - we changed up the fields so we don't have things like headache/dizziness right now for example.

I think there's some UI-type bug causing `openComment` not to save - whenever you enter text and then click out of the `TextField` it'll save properly, I believe. I'm not sure why this is, because either way, when you just `console.log(action.survey.openComment)` in the associated reducer case, it'll print out the text whether you click away or not... 

I'm thinking maybe when we make a request to Gaia, it's not picking up the most up-to-date state? I was going to see if that was failing on others' machines after merging and make a bug report if so, but it seems like it's already there. If I can figure something out semi-quickly, I'll add that in this PR as well

**Comment by AdhamAH** [comment]
@SomeMoosery I was having the last comment but I had to restart the server and it worked fine.
As for the comment, if you make two surveys, the comment in the first one will show in the second survey. This has to do as you said, this means it is not pulling the most recent data

**Comment by SomeMoosery** [comment]
I think I'm going to merge in these changes - I fixed up the UI at least to a usable degree. I think going forward, we could split up the remaining work into two separate issues: a bug for the `openComment` issue, and a feature request to update the styling on desktop (and in general)

**Pull request merged**
