### PR TITLE
Add bootstrap dependency

### PR DESCRIPTION
**Pull request by sedmo**

### CODE REVIEW

**Comment by SomeMoosery** [comment]
So I've never used yarn before - we still need to import bootstrap in either `index.js` or `App.js` right? Might be worthwhile doing in this PR as well just to set a baseline

**Comment by SomeMoosery** [comment]
Also be sure to rebase off master, since it looks like you have merge conflicts now. 

If you need any help with that lmk!

**Comment by sedmo** [comment]
I did base off master. it seems the issue is from the one line I added in the package.json

**Comment by tesla809** [comment]
We can add bootstrap dependency similar to this article. 
https://www.techiediaries.com/react-bootstrap/

So `yarn add boostrap`

Then in `src/index.js` add  `import 'bootstrap/dist/css/bootstrap.min.css';`

**Comment by sedmo** [comment]
PR #35 will take place for this. Closing

**Pull request closed without merging**
