### PR TITLE
Fix bug: education cards cut off on smaller screens, issue #576

### LINKED ISSUE #576: Cards on small screens cut off
### Prerequisites

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Since scrolling is disabled on the flashcards component, sometimes cards are cut off on very small screens.

### Steps to Reproduce

1. Log in 
2. Go to flashcards
3. Inspect, make screen very small

**Expected behavior:**

We should allow all users to be able to scroll to see the full card

**Actual behavior:**

Often full cards aren't visible

**Reproduces how often:**

100% on relevant screen sizes

### Versions

1.0.1

### PR DESCRIPTION
**Pull request by gitalink**
Fix bug where cards cut off on smaller screens

# ⚠️ __IMPORTANT: Please do not create a Pull Request without creating an issue first.__

All changes need to be discusssed before proceeding. Failure to do so may result in the pull request being rejected.

Please be sure to review our [Code of Conduct](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CODE_OF_CONDUCT.md), [Contributing Guidelines](https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md), and [Support documentation](https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md) before submitting a pull request.

-----

## Please include the issue number the pull request fixes by replacing YOUR-ISSUE-HERE in the text below.

Fixes #576 

## Summary

On smaller screens, the cards were cut off on the bottom. I have adjusted cards sizing for screens with a max width of 400 using Material UI theme.breakpoints.down(400). ## Details

I picked 400 as it includes phones 6/7/8, and does not include Iphones 6/7/8plus. 

I also changed the Facts cards title style to match Quiz cards title, as on smaller screens the h4 font was too big compared to the body text size. 

## Test Plan (required)
I tested on Chrome console and my iPhone8. 

## Final Checklist

- [x ] For CoronaTracker, did you bump the version in `package.json`?
    - Update the second decimal for a major change
    - Update the third decimal for a minor change
    - Numbers can go past 9, e.g. `1.0.9` => `1.0.10`
    - For more info, read about [Semantic Versioning](https://semver.org/)
- [n/a] Did you add any new tests as necessary?
- [x ] Is your PR rebased off the most current master?
- [- ] Have you squashed all commits? _(can be done at merge)_
- [x] Did you use `yarn` not `npm`? _(important!)_
- [x] Did you use Material-UI wherever possible?
- [x] Did you run `yarn lint` on the code?
- [x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by gitalink** [comment]
IMG_1182
This is how it looks on my iPhone8. It would be nice for someone else to test other small screens.

**Comment by acthelemann** [comment]
I feel like this should scroll on overflow just in case, but I'll accept it

**Comment by gitalink** [comment]
I removed yarn.lock.

**Comment by gitalink** [comment]
I will check on scrolling, I agree it should scroll just in case. I thought it did scroll.

**Pull request merged**
