### PR TITLE
update calendar month hover font to black

### LINKED ISSUE #542: Update yellow color on calendar
### Prerequisites 

* [x] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in QA
    * Followed all applicable steps in the TROUBLESHOOTING guide: TODO
    * Checked for relevant discussions on Discord: <https://discord.gg/pPERUuv>
    * Checked that your issue isn't already filed: <https://github.com/COVID-19-electronic-health-system/Corona-tracker/issues>

### Description

Right now there are two yellow colors in use for the calendar: [#ffff76](https://www.colorhexa.com/ffff76) and [#ffffa9](https://www.colorhexa.com/ffffa9).

```css
.react-calendar__tile--now {
  background-color: #ffff76;
  color: white;
}
.react-calendar__tile--now:enabled:hover,
.react-calendar__tile--now:enabled:focus {
  background-color: #ffffa9;
  color: white;
}
```
Under the right conditions I can select and make a single square yellow of the calendar yellow and the white text is near impossible to read. You can see it in the gif below on the month selection screen as well:

### Steps to Reproduce

1. Open the calendar screen
2. Select multiple dates, seems to be more common if I "slide" from one day to another
3. Observe the hard to read text

**Expected behavior:**

I expect the text to be legible or a blue color to be used instead.

**Actual behavior:**

The background stays yellow for the active item, and the white text is hard to read.

**Reproduces how often:**

50%

### Additional Information

Idea 1 would be to set the yellow background to always use `color: black` so at least the text is readable when this happens.

Idea 2 would be to replace the yellow with a lighter blue color, but the text may need to be darker in that case as well.

### PR DESCRIPTION
**Pull request by johnemurphy1**
# ⚠️ __IMPORTANT: Please do not create a Pull Request without creating an Issue first.__

All changes need to be discussed before proceeding. Failure to do so may result in the pull request being rejected.

Before submitting a pull request, please be sure to review:
- Our Code of Conduct: https://github.com/COVID-19-electronic-health-system/.github/blob/master/CODE_OF_CONDUCT.md
- Our Contributing Guidelines: https://github.com/COVID-19-electronic-health-system/.github/blob/master/CONTRIBUTING.md
- Our Support documentation: https://github.com/COVID-19-electronic-health-system/.github/blob/master/SUPPORT.md

-----

## Please include the issue number the pull request fixes by replacing YOUR-ISSUE-HERE in the text below.

Fixes #542

## Summary:
This fixes the white font against yellow background on month in calendar when user hovers over month by making font black.
## Details

See summary above.

## Test Plan (required)

Minor CSS change.

## Final Checklist

- [ ] For CoronaTracker, did you bump the version in `package.json`?
    - Update the second decimal for a major change
    - Update the third decimal for a minor change
    - Numbers can go past 9, e.g. `1.0.9` => `1.0.10`
    - For more info, read about [Semantic Versioning](https://semver.org/)
- [ ] Did you add any new tests as necessary?
- [ x] Is your PR rebased off the most current master?
- [ x] Have you squashed all commits? _(can be done at merge)_
- [ x] Did you use `yarn` not `npm`? _(important!)_
- [ x] Did you use Material-UI wherever possible?
- [x ] Did you run `yarn lint` on the code?
- [ x] Did you run all of your most recent changes locally to make sure everything is working?

### CODE REVIEW

**Comment by johnemurphy1** [comment]
@AdhamAH I realize I didn't change the font color for all the different components now. Is that what you are saying doesn't answer issue #542? Please let me know.

**Comment by AdhamAH** [comment]
Do you see the yellow colour? I think this is what the issue about

**Comment by johnemurphy1** [comment]
yes, i see the yellow color. the proposed solutions were  (on the hover) 1. change the font color to black or 2. change the background to dark blue.

**Comment by SomeMoosery** [comment]
I personally don't think I read the issue carefully enough, but I'm not sure why we'd want that background to be yellow. @whoabuddy was there any reason you'd propose changing the text as opposed to the background color? I'm not sure if the yellow is capturing any information here 🤔

**Comment by acthelemann** [comment]
> Did you add this `translationsFormatted.json` file? If not you need to rebase off master.

Even if you did, we shouldn't add that file in this commit.

Also, I don't think your change makes the font color black when necessary. Nothing seems to have changed when I run it locally. Can you post a screenshot/gif of it working on your end?

**Comment by johnemurphy1** [comment]
@SomeMoosery and @AdhamAH  what is the consensus on how this issue should be handled? Change the background color to the darker blue? Could you please let me know? Then, I'll work on that.

@SomeMoosery  and @acthelemann . The translationsFormatted.json file was something I worked on with @awu556  for @salvolpe. I believe @ngiangre and @BrianHHough (?) took it over and that file needs to be sunsetted. It was started a while back and left on the shelf. Should not have been in this PR.  My mistake.

**Comment by ngiangre** [comment]
@johnemurphy1 yes we've taken that and used it to refactor into the translation.json files in client/locales/

**Comment by acthelemann** [comment]
@johnemurphy1 I think you should mimic the styling on [this hasActive class](https://github.com/COVID-19-electronic-health-system/Corona-tracker/blob/master/client/src/css/Calendar.css#L143), so you'll be changing the default background color and the background color on hover/focus.

@AdhamAH @SomeMoosery @whoabuddy Thoughts?

The styling on the calendar is messy in general and should be consolidated all in `Calendar.jsx`. `Calendar.css` should be removed. That can be done in another PR/issue, though.

**Comment by AdhamAH** [comment]
> The styling on the calendar is messy in general and should be consolidated all in `Calendar.jsx`. `Calendar.css` should be removed. That can be done in another PR/issue, though.

@acthelemann  I totally agree and I actually took a look before how could it be done but I was busy to do it. But this is out of #542 scoop.

@johnemurphy1 what needs to be done with this issue is changing the background of the current date of the day/month/year (yellow) when selecting a different date and hover over the current date.

**Comment by whoabuddy** [comment]
> I personally don't think I read the issue carefully enough, but I'm not sure why we'd want that background to be yellow. @whoabuddy was there any reason you'd propose changing the text as opposed to the background color? I'm not sure if the yellow is capturing any information here

Just for simplicity - black text would make it readable, but eliminating the yellow is better!

**Comment by johnemurphy1** [comment]
Updated the hover with new dark blue color to make white font legible.

**Pull request merged**
