### PR TITLE
fixes: #223 survey is now centered

### PR DESCRIPTION
**Pull request by crispinamuriel**
Fix: Survey page is now centered

### CODE REVIEW

**Comment by crispinamuriel** [comment]
Screen Shot 2020-03-26 at 11 50 25 PM

**Comment by crispinamuriel** [comment]
Screen Shot 2020-03-27 at 2 56 45 PM

**Comment by crispinamuriel** [comment]
I've rebased, Thanks Carter.

**Comment by SomeMoosery** [comment]
Hm, it looks like there's still old files being changed (for example, in master now we're using `authenticated` not `authed` in `App.js`... did you pull in the most recent changes from upstream/master before rebasing? I'm not sure if that's exactly the fix, but might point you in the right direction. Apologies, I don't have too much experience working with git on forked copies.

**Pull request closed without merging**
